<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class BidangDivisi extends Seeder
{
    public function run()
    {
        //
        $data = [
            //Rohis
            [
                'id_bidang_divisi' => 'BD001',
                'id_user' => '16',
                'id_ukm' => 'UKM001',
                'id_ormawa' => 'OM002',
                'nama_bidang_divisi' => 'Bidang Rohani Islam',
                'kontak_bidang_divisi' => '',
                'desc_ormawa' => '',
            ],
            [
                'id_bidang_divisi' => 'BD002',
                'id_user' => '17',
                'id_ukm' => 'UKM001',
                'id_ormawa' => 'OM002',
                'nama_bidang_divisi' => 'Bidang Rohani Kristen',
                'kontak_bidang_divisi' => '',
                'desc_ormawa' => '',
            ],
            [
                'id_bidang_divisi' => 'BD003',
                'id_user' => '18',
                'id_ukm' => 'UKM001',
                'id_ormawa' => 'OM002',
                'nama_bidang_divisi' => 'Bidang Rohani Hindu',
                'kontak_bidang_divisi' => '',
                'desc_ormawa' => '',
            ],
            //Kesenian
            [
                'id_bidang_divisi' => 'BD004',
                'id_user' => '19',
                'id_ukm' => 'UKM002',
                'id_ormawa' => 'OM002',
                'nama_bidang_divisi' => 'Bidang Excelsior',
                'kontak_bidang_divisi' => '',
                'desc_ormawa' => '',
            ],
            [
                'id_bidang_divisi' => 'BD005',
                'id_user' => '20',
                'id_ukm' => 'UKM002',
                'id_ormawa' => 'OM002',
                'nama_bidang_divisi' => 'Bidang Teater Antik',
                'kontak_bidang_divisi' => '',
                'desc_ormawa' => '',
            ],
            [
                'id_bidang_divisi' => 'BD006',
                'id_user' => '21',
                'id_ukm' => 'UKM002',
                'id_ormawa' => 'OM002',
                'nama_bidang_divisi' => 'Bidang Paradise',
                'kontak_bidang_divisi' => '',
                'desc_ormawa' => '',
            ],
            [
                'id_bidang_divisi' => 'BD007',
                'id_user' => '22',
                'id_ukm' => 'UKM002',
                'id_ormawa' => 'OM002',
                'nama_bidang_divisi' => 'Bidang Xbar',
                'kontak_bidang_divisi' => '',
                'desc_ormawa' => '',
            ],
            //UKM Wirus
            [
                'id_bidang_divisi' => 'BD008',
                'id_user' => '23',
                'id_ukm' => 'UKM003',
                'id_ormawa' => 'OM002',
                'nama_bidang_divisi' => 'Bidang Kewirausahaan',
                'kontak_bidang_divisi' => '',
                'desc_ormawa' => '',
            ],
            //UKM MK
            [
                'id_bidang_divisi' => 'BD009',
                'id_user' => '24',
                'id_ukm' => 'UKM004',
                'id_ormawa' => 'OM002',
                'nama_bidang_divisi' => 'Bidang Media Kampus',
                'kontak_bidang_divisi' => '',
                'desc_ormawa' => '',
            ],
            //UKM Olahraga
            [
                'id_bidang_divisi' => 'BD0010',
                'id_user' => '25',
                'id_ukm' => 'UKM005',
                'id_ormawa' => 'OM002',
                'nama_bidang_divisi' => 'Bidang Esport',
                'kontak_bidang_divisi' => '',
                'desc_ormawa' => '',
            ],
            [
                'id_bidang_divisi' => 'BD0011',
                'id_user' => '26',
                'id_ukm' => 'UKM005',
                'id_ormawa' => 'OM002',
                'nama_bidang_divisi' => 'Divisi Senam',
                'kontak_bidang_divisi' => '',
                'desc_ormawa' => '',
            ],
            [
                'id_bidang_divisi' => 'BD0012',
                'id_user' => '27',
                'id_ukm' => 'UKM005',
                'id_ormawa' => 'OM002',
                'nama_bidang_divisi' => 'Divisi Futsal',
                'kontak_bidang_divisi' => '',
                'desc_ormawa' => '',
            ],
            [
                'id_bidang_divisi' => 'BD0013',
                'id_user' => '28',
                'id_ukm' => 'UKM005',
                'id_ormawa' => 'OM002',
                'nama_bidang_divisi' => 'Divisi Bulstik',
                'kontak_bidang_divisi' => '',
                'desc_ormawa' => '',
            ],
            [
                'id_bidang_divisi' => 'BD0014',
                'id_user' => '29',
                'id_ukm' => 'UKM005',
                'id_ormawa' => 'OM002',
                'nama_bidang_divisi' => 'Divisi Silat',
                'kontak_bidang_divisi' => '',
                'desc_ormawa' => '',
            ],
            [
                'id_bidang_divisi' => 'BD0015',
                'id_user' => '30',
                'id_ukm' => 'UKM005',
                'id_ormawa' => 'OM002',
                'nama_bidang_divisi' => 'Divisi Basket',
                'kontak_bidang_divisi' => '',
                'desc_ormawa' => '',
            ],
            [
                'id_bidang_divisi' => 'BD0016',
                'id_user' => '31',
                'id_ukm' => 'UKM005',
                'id_ormawa' => 'OM002',
                'nama_bidang_divisi' => 'Divisi Catur',
                'kontak_bidang_divisi' => '',
                'desc_ormawa' => '',
            ],
            [
                'id_bidang_divisi' => 'BD0017',
                'id_user' => '32',
                'id_ukm' => 'UKM005',
                'id_ormawa' => 'OM002',
                'nama_bidang_divisi' => 'Divisi Voli',
                'kontak_bidang_divisi' => '',
                'desc_ormawa' => '',
            ],
            [
                'id_bidang_divisi' => 'BD0018',
                'id_user' => '33',
                'id_ukm' => 'UKM005',
                'id_ormawa' => 'OM002',
                'nama_bidang_divisi' => 'Divisi Tenis Meja',
                'kontak_bidang_divisi' => '',
                'desc_ormawa' => '',
            ],
            [
                'id_bidang_divisi' => 'BD0019',
                'id_user' => '34',
                'id_ukm' => 'UKM005',
                'id_ormawa' => 'OM002',
                'nama_bidang_divisi' => 'Divisi Bridge',
                'kontak_bidang_divisi' => '',
                'desc_ormawa' => '',
            ],
            [
                'id_bidang_divisi' => 'BD0020',
                'id_user' => '35',
                'id_ukm' => 'UKM005',
                'id_ormawa' => 'OM002',
                'nama_bidang_divisi' => 'Divisi Tenis Lapangan',
                'kontak_bidang_divisi' => '',
                'desc_ormawa' => '',
            ],
            [
                'id_bidang_divisi' => 'BD0021',
                'id_user' => '36',
                'id_ukm' => 'UKM005',
                'id_ormawa' => 'OM002',
                'nama_bidang_divisi' => 'DIvisi Billiard',
                'kontak_bidang_divisi' => '',
                'desc_ormawa' => '',
            ],
            //Udikbud
            [
                'id_bidang_divisi' => 'BD0022',
                'id_user' => '37',
                'id_ukm' => 'UKM006',
                'id_ormawa' => 'OM002',
                'nama_bidang_divisi' => 'Bidang Komnet',
                'kontak_bidang_divisi' => '',
                'desc_ormawa' => '',
            ],
            [
                'id_bidang_divisi' => 'BD0023',
                'id_user' => '38',
                'id_ukm' => 'UKM006',
                'id_ormawa' => 'OM002',
                'nama_bidang_divisi' => 'Bidang Bimbel',
                'kontak_bidang_divisi' => '',
                'desc_ormawa' => '',
            ],
            [
                'id_bidang_divisi' => 'BD0024',
                'id_user' => '39',
                'id_ukm' => 'UKM006',
                'id_ormawa' => 'OM002',
                'nama_bidang_divisi' => 'Bidang Forkas',
                'kontak_bidang_divisi' => '',
                'desc_ormawa' => '',
            ],
            [
                'id_bidang_divisi' => 'BD0025',
                'id_user' => '40',
                'id_ukm' => 'UKM006',
                'id_ormawa' => 'OM002',
                'nama_bidang_divisi' => 'Divisi SES',
                'kontak_bidang_divisi' => '',
                'desc_ormawa' => '',
            ],
            [
                'id_bidang_divisi' => 'BD0026',
                'id_user' => '41',
                'id_ukm' => 'UKM006',
                'id_ormawa' => 'OM002',
                'nama_bidang_divisi' => 'Divisi Nihongobu',
                'kontak_bidang_divisi' => '',
                'desc_ormawa' => '',
            ],
            //PMKL
            [
                'id_bidang_divisi' => 'BD0027',
                'id_user' => '42',
                'id_ukm' => 'UKM007',
                'id_ormawa' => 'OM002',
                'nama_bidang_divisi' => 'Bidang KSR',
                'kontak_bidang_divisi' => '',
                'desc_ormawa' => '',
            ],
            [
                'id_bidang_divisi' => 'BD0028',
                'id_user' => '43',
                'id_ukm' => 'UKM007',
                'id_ormawa' => 'OM002',
                'nama_bidang_divisi' => 'Bidang Cheby',
                'kontak_bidang_divisi' => '',
                'desc_ormawa' => '',
            ],
        ];

        $this->db->table('bidang_divisi')->insertBatch($data);  
    }
}
