<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class User extends Seeder
{
    public function run()
    {
        $data = [
            [
                'id_user' => '1',
                'username' => 'admin',
                'password' => '$2y$10$PausAngEI/fBjRZ5djHwEOj2ws8ylPFqBicXCpmvBBbknQrVcbuv6',
                'role' => 'Admin',
                'nama_tampil' => 'Admin',
            ],
            [
                'id_user' => '2',
                'username' => 'DPM',
                'password' => '$2y$10$PausAngEI/fBjRZ5djHwEOj2ws8ylPFqBicXCpmvBBbknQrVcbuv6',
                'role' => 'BPH',
                'nama_tampil' => 'DPM',
            ],
            [
                'id_user' => '3',
                'username' => 'SEMA',
                'password' => '$2y$10$PausAngEI/fBjRZ5djHwEOj2ws8ylPFqBicXCpmvBBbknQrVcbuv6',
                'role' => 'BPH',
                'nama_tampil' => 'SEMA',
            ],
            [
                'id_user' => '4',
                'username' => 'SPD',
                'password' => '$2y$10$PausAngEI/fBjRZ5djHwEOj2ws8ylPFqBicXCpmvBBbknQrVcbuv6',
                'role' => 'BPH',
                'nama_tampil' => 'SPD',
            ],
            [
                'id_user' => '5',
                'username' => 'MENWA',
                'password' => '$2y$10$PausAngEI/fBjRZ5djHwEOj2ws8ylPFqBicXCpmvBBbknQrVcbuv6',
                'role' => 'BPH',
                'nama_tampil' => 'MENWA',
            ],
            [
                'id_user' => '6',
                'username' => 'wahyudin',
                'password' => '$2y$10$PausAngEI/fBjRZ5djHwEOj2ws8ylPFqBicXCpmvBBbknQrVcbuv6',
                'role' => 'UPK',
                'nama_tampil' => 'Pak Wahyudin',
            ],
            [
                'id_user' => '7',
                'username' => 'firdaus',
                'password' => '$2y$10$PausAngEI/fBjRZ5djHwEOj2ws8ylPFqBicXCpmvBBbknQrVcbuv6',
                'role' => 'UPK',
                'nama_tampil' => 'Pak Firdaus',
            ], 
            [
                'id_user' => '8',
                'username' => 'sekretarisupk',
                'password' => '$2y$10$PausAngEI/fBjRZ5djHwEOj2ws8ylPFqBicXCpmvBBbknQrVcbuv6',
                'role' => 'UPK',
                'nama_tampil' => 'Sekretaris',
            ],
            [
                'id_user' => '9',
                'username' => 'ukmkerohanian',
                'password' => '$2y$10$PausAngEI/fBjRZ5djHwEOj2ws8ylPFqBicXCpmvBBbknQrVcbuv6',
                'role' => 'BPH',
                'nama_tampil' => 'UKM Kerohanian',
            ],
            [
                'id_user' => '10',
                'username' => 'ukmkesenian',
                'password' => '$2y$10$PausAngEI/fBjRZ5djHwEOj2ws8ylPFqBicXCpmvBBbknQrVcbuv6',
                'role' => 'BPH',
                'nama_tampil' => 'UKM Kesenian',
            ],
            [
                'id_user' => '11',
                'username' => 'ukmkewirausahaan',
                'password' => '$2y$10$PausAngEI/fBjRZ5djHwEOj2ws8ylPFqBicXCpmvBBbknQrVcbuv6',
                'role' => 'BPH',
                'nama_tampil' => 'UKM Kewirausahaan',
            ],
            [
                'id_user' => '12',
                'username' => 'ukmmediakampus',
                'password' => '$2y$10$PausAngEI/fBjRZ5djHwEOj2ws8ylPFqBicXCpmvBBbknQrVcbuv6',
                'role' => 'BPH',
                'nama_tampil' => 'UKM Media Kampus',
            ],
            [
                'id_user' => '13',
                'username' => 'ukmolahraga',
                'password' => '$2y$10$PausAngEI/fBjRZ5djHwEOj2ws8ylPFqBicXCpmvBBbknQrVcbuv6',
                'role' => 'BPH',
                'nama_tampil' => 'UKM Olahraga',
            ],
            [
                'id_user' => '14',
                'username' => 'ukmdikbud',
                'password' => '$2y$10$PausAngEI/fBjRZ5djHwEOj2ws8ylPFqBicXCpmvBBbknQrVcbuv6',
                'role' => 'BPH',
                'nama_tampil' => 'UKM Pendidikan dan Kebudayaan',
            ],
            [
                'id_user' => '15',
                'username' => 'ukmpmkl',
                'password' => '$2y$10$PausAngEI/fBjRZ5djHwEOj2ws8ylPFqBicXCpmvBBbknQrVcbuv6',
                'role' => 'BPH',
                'nama_tampil' => 'UKM PMKL',
            ],
            [
                'id_user' => '16',
                'username' => 'rohaniislam',
                'password' => '$2y$10$PausAngEI/fBjRZ5djHwEOj2ws8ylPFqBicXCpmvBBbknQrVcbuv6',
                'role' => 'BPH',
                'nama_tampil' => 'Bidang Kerohanian Islam',
            ],
            [
                'id_user' => '17',
                'username' => 'rohanikristen',
                'password' => '$2y$10$PausAngEI/fBjRZ5djHwEOj2ws8ylPFqBicXCpmvBBbknQrVcbuv6',
                'role' => 'BPH',
                'nama_tampil' => 'Bidang Kerohanian Kristen',
            ],
            [
                'id_user' => '18',
                'username' => 'rohanihindu',
                'password' => '$2y$10$PausAngEI/fBjRZ5djHwEOj2ws8ylPFqBicXCpmvBBbknQrVcbuv6',
                'role' => 'BPH',
                'nama_tampil' => 'Bidang Kerohanian Hindu',
            ],
            [
                'id_user' => '19',
                'username' => 'excelsior',
                'password' => '$2y$10$PausAngEI/fBjRZ5djHwEOj2ws8ylPFqBicXCpmvBBbknQrVcbuv6',
                'role' => 'BPH',
                'nama_tampil' => 'Bidang Excelsior',
            ],
            [
                'id_user' => '20',
                'username' => 'teaterantik',
                'password' => '$2y$10$PausAngEI/fBjRZ5djHwEOj2ws8ylPFqBicXCpmvBBbknQrVcbuv6',
                'role' => 'BPH',
                'nama_tampil' => 'Bidang Teater Antik',
            ],
            [
                'id_user' => '21',
                'username' => 'paradise',
                'password' => '$2y$10$PausAngEI/fBjRZ5djHwEOj2ws8ylPFqBicXCpmvBBbknQrVcbuv6',
                'role' => 'BPH',
                'nama_tampil' => 'Bidang Paradise',
            ],
            [
                'id_user' => '22',
                'username' => 'xbar',
                'password' => '$2y$10$PausAngEI/fBjRZ5djHwEOj2ws8ylPFqBicXCpmvBBbknQrVcbuv6',
                'role' => 'BPH',
                'nama_tampil' => 'Bidang Xbar',
            ],
            [
                'id_user' => '23',
                'username' => 'wirus',
                'password' => '$2y$10$PausAngEI/fBjRZ5djHwEOj2ws8ylPFqBicXCpmvBBbknQrVcbuv6',
                'role' => 'BPH',
                'nama_tampil' => 'Bidang Kewirausahaan',
            ],
            [
                'id_user' => '24',
                'username' => 'mediakampus',
                'password' => '$2y$10$PausAngEI/fBjRZ5djHwEOj2ws8ylPFqBicXCpmvBBbknQrVcbuv6',
                'role' => 'BPH',
                'nama_tampil' => 'Bidang Media Kampus',
            ],
            [
                'id_user' => '25',
                'username' => 'esport',
                'password' => '$2y$10$PausAngEI/fBjRZ5djHwEOj2ws8ylPFqBicXCpmvBBbknQrVcbuv6',
                'role' => 'BPH',
                'nama_tampil' => 'Bidang Esport',
            ],
            [
                'id_user' => '26',
                'username' => 'senam',
                'password' => '$2y$10$PausAngEI/fBjRZ5djHwEOj2ws8ylPFqBicXCpmvBBbknQrVcbuv6',
                'role' => 'BPH',
                'nama_tampil' => 'Divisi Senam',
            ],
            [
                'id_user' => '27',
                'username' => 'futsal',
                'password' => '$2y$10$PausAngEI/fBjRZ5djHwEOj2ws8ylPFqBicXCpmvBBbknQrVcbuv6',
                'role' => 'BPH',
                'nama_tampil' => 'Divisi Futsal',
            ],
            [
                'id_user' => '28',
                'username' => 'bulstik',
                'password' => '$2y$10$PausAngEI/fBjRZ5djHwEOj2ws8ylPFqBicXCpmvBBbknQrVcbuv6',
                'role' => 'BPH',
                'nama_tampil' => 'Divisi Bulstik',
            ],
            [
                'id_user' => '29',
                'username' => 'silat',
                'password' => '$2y$10$PausAngEI/fBjRZ5djHwEOj2ws8ylPFqBicXCpmvBBbknQrVcbuv6',
                'role' => 'BPH',
                'nama_tampil' => 'Divisi Silat',
            ],
            [
                'id_user' => '30',
                'username' => 'basket',
                'password' => '$2y$10$PausAngEI/fBjRZ5djHwEOj2ws8ylPFqBicXCpmvBBbknQrVcbuv6',
                'role' => 'BPH',
                'nama_tampil' => 'Divisi Basket',
            ],
            [
                'id_user' => '31',
                'username' => 'catur',
                'password' => '$2y$10$PausAngEI/fBjRZ5djHwEOj2ws8ylPFqBicXCpmvBBbknQrVcbuv6',
                'role' => 'BPH',
                'nama_tampil' => 'Divisi Catur',
            ],
            [
                'id_user' => '32',
                'username' => 'voli',
                'password' => '$2y$10$PausAngEI/fBjRZ5djHwEOj2ws8ylPFqBicXCpmvBBbknQrVcbuv6',
                'role' => 'BPH',
                'nama_tampil' => 'Divisi Voli',
            ],
            [
                'id_user' => '33',
                'username' => 'tenismeja',
                'password' => '$2y$10$PausAngEI/fBjRZ5djHwEOj2ws8ylPFqBicXCpmvBBbknQrVcbuv6',
                'role' => 'BPH',
                'nama_tampil' => 'Divisi Tenis Meja',
            ],
            [
                'id_user' => '34',
                'username' => 'bridge',
                'password' => '$2y$10$PausAngEI/fBjRZ5djHwEOj2ws8ylPFqBicXCpmvBBbknQrVcbuv6',
                'role' => 'BPH',
                'nama_tampil' => 'Divisi Bridge',
            ],
            [
                'id_user' => '35',
                'username' => 'tenislapangan',
                'password' => '$2y$10$PausAngEI/fBjRZ5djHwEOj2ws8ylPFqBicXCpmvBBbknQrVcbuv6',
                'role' => 'BPH',
                'nama_tampil' => 'Divisi Tenis Lapangan',
            ],
            [
                'id_user' => '36',
                'username' => 'billiard',
                'password' => '$2y$10$PausAngEI/fBjRZ5djHwEOj2ws8ylPFqBicXCpmvBBbknQrVcbuv6',
                'role' => 'BPH',
                'nama_tampil' => 'Divisi Billiard',
            ],
            [
                'id_user' => '37',
                'username' => 'komnet',
                'password' => '$2y$10$PausAngEI/fBjRZ5djHwEOj2ws8ylPFqBicXCpmvBBbknQrVcbuv6',
                'role' => 'BPH',
                'nama_tampil' => 'Bidang Komnet',
            ],
            [
                'id_user' => '38',
                'username' => 'bimbel',
                'password' => '$2y$10$PausAngEI/fBjRZ5djHwEOj2ws8ylPFqBicXCpmvBBbknQrVcbuv6',
                'role' => 'BPH',
                'nama_tampil' => 'Bidang Bimbel',
            ],
            [
                'id_user' => '39',
                'username' => 'forkas',
                'password' => '$2y$10$PausAngEI/fBjRZ5djHwEOj2ws8ylPFqBicXCpmvBBbknQrVcbuv6',
                'role' => 'BPH',
                'nama_tampil' => 'Bidang Forkas',
            ],
            [
                'id_user' => '40',
                'username' => 'ses',
                'password' => '$2y$10$PausAngEI/fBjRZ5djHwEOj2ws8ylPFqBicXCpmvBBbknQrVcbuv6',
                'role' => 'BPH',
                'nama_tampil' => 'Divisi SES',
            ],
            [
                'id_user' => '41',
                'username' => 'nihongobu',
                'password' => '$2y$10$PausAngEI/fBjRZ5djHwEOj2ws8ylPFqBicXCpmvBBbknQrVcbuv6',
                'role' => 'BPH',
                'nama_tampil' => 'Divisi Nihongobu',
            ],
            [
                'id_user' => '42',
                'username' => 'ksr',
                'password' => '$2y$10$PausAngEI/fBjRZ5djHwEOj2ws8ylPFqBicXCpmvBBbknQrVcbuv6',
                'role' => 'BPH',
                'nama_tampil' => 'Bidang KSR',
            ],
            [
                'id_user' => '43',
                'username' => 'cheby',
                'password' => '$2y$10$PausAngEI/fBjRZ5djHwEOj2ws8ylPFqBicXCpmvBBbknQrVcbuv6',
                'role' => 'BPH',
                'nama_tampil' => 'Bidang Cheby',
            ],
            [
                'id_user' => '44',
                'username' => 'BAAK',
                'password' => '$2y$10$PausAngEI/fBjRZ5djHwEOj2ws8ylPFqBicXCpmvBBbknQrVcbuv6',
                'role' => 'BAAK',
                'nama_tampil' => 'BAAK',
            ],
            [
                'id_user' => '45',
                'username' => 'wadir3',
                'password' => '$2y$10$PausAngEI/fBjRZ5djHwEOj2ws8ylPFqBicXCpmvBBbknQrVcbuv6',
                'role' => 'wadir',
                'nama_tampil' => 'Wakil Direktur III',
            ],
            [
                'id_user' => '46',
                'username' => 'direktur',
                'password' => '$2y$10$PausAngEI/fBjRZ5djHwEOj2ws8ylPFqBicXCpmvBBbknQrVcbuv6',
                'role' => 'direktur',
                'nama_tampil' => 'Direktur Polstat STIS',
            ],
        ];

        $this->db->table('users')->insertBatch($data);
    }
}
